routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});



Route::group(['prefix' => 'cust','as'=>'customer.'], function () {
    Auth::routes(['verify' => true]);
});

Route::group(['as' => 'customer.'], function () {
    Route::get('/', 'CustomerController@index')->name("home");
    
    
    Route::group(['middleware' => 'customer', 'prefix' => 'cust'], function () {
        Route::get('/demo', 'DemoController@index');
        Route::get('/buatundangan', 'CustomerController@register')->name('buatundangan');
        Route::post('/tambahundangan', 'CustomerController@store')->name('tambahundangan');
    });
});


auth::routes();

Route::group(['prefix' => 'admin'], function () {
    Route::get('login', 'AuthAdminController@showLoginForm')->name('admin.login');
    Route::post('login', 'AuthAdminController@login')->name('admin.postlogin');
    Route::post('logout', 'AuthAdminController@logout')->name('admin.logout');
});

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {
    Route::resource('/', 'AdminController');
    Route::resource('/agama', 'AgamaController');
    Route::resource('/sambutan', 'SambutanController');
    Route::resource('/pesanan', 'PesananController');
    Route::put('/pesanan/ubahStatus/{id}', 'PesananController@changeStatus')->name('pesanan.changeStatus');
});

// Route::group(['prefix'=>'/admin','middleware'=>'admin'],function(){
//     Route::resource('/','AdminController');
// });

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/{domain}', 'CustomerController@undangan');

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    //
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Pesanan;
use App\Agama;
use App\Http\Requests\UndanganRequest;
use App\Images;
use Illuminate\Http\Request;
use Auth;
use App\Sambutan;
class CustomerController extends Controller
{
    public function index()
    {
        return view("customer.home");
    }

    public function register()
    {
        $agama = Agama::all();
        return view("customer.register",compact('agama'));
    }

    public function store(UndanganRequest $request)
    {

        $sambutan = Sambutan::where('agama_id',$request->agama)->first();
    
        // $data['photo'] = $request->file('gambar');
        // $data['gallery'] = $request->file('gallery');
        // dd($data);


        $phone_code = 62;
        $strwa = $request->whatsapp_number;
        $arr = array($phone_code,$strwa); 
        $wa = implode($arr);
        
        $tanggal = $request->date;
        $waktu = $request->time;
        
        $combinedDT = date('Y-m-d H:i:s', strtotime("$tanggal $waktu"));

        
	    $data = new Pesanan;
        $data->subdomain = $request->subdomain;
        $data->guy_nickname = $request->guy_nickname;
        $data->girl_nickname = $request->girl_nickname;
        $data->datetime_start = $combinedDT;
        $data->datetime_end = $combinedDT;
        $data->address = $request->address;
        $data->user_id = Auth::id();
        // $data->google_maps = $request->google_maps;
        $data->latitude = $request->latitude;
        $data->longitude = $request->longitude;
        $data->whatsapp_number = $wa;
        $data->sambutan_id = $sambutan->id;
        $data->harga_id = 1;
        if($request->hasfile('bukti_pembayaran'))
         {
            foreach($request->file('bukti_pembayaran') as $file)
            {
                $namePayment = time().'_'.$file->getClientOriginalName();
                $file->move(public_path().'/demos/payment/', $namePayment);  
                $hasil[] = $namePayment; 
                $data->payment_proof =$namePayment;
            }
         }
          
        $data->save();
        
        if($request->hasfile('gambar'))
         {
            foreach($request->file('gambar') as $file)
            {
                $name = time().'_'.$file->getClientOriginalName();
                $file->move(public_path().'/demos/foto/', $name);  
                $hasil[] = $name;
                $file= new Images();
                $file->undangan_id=$data->id;
                $file->image= $name;
                $file->status='0';
                $file->save();  
            }
         }

        if($request->hasfile('gallery'))
         {
            foreach($request->file('gallery') as $file)
            {
                $name = time().'_'.$file->getClientOriginalName();
                $file->move(public_path().'/demos/foto/', $name);  
                $hasil[] = $name; 
                $file= new Images();
                $file->undangan_id=$data->id;
                $file->image= $name;
                $file->status='1';
                $file->save(); 
            }
         }

         
    
	    return redirect('/')->with('success','Pembuatan berhasil dilakukan tunggu admin melakukan verifikasi terhadap bukti pembayaran');
 
    }


    public function undangan($domain)
    {
        $data = Pesanan::where('subdomain', $domain)->where('status', '2')->get();
        $undangan = Pesanan::where('subdomain', $domain)->first();
        // return $undangan;
        if ($data->count() == 0) {
            return redirect()->route("customer.home");
        } else {
            return view("customer.undangan", compact("undangan"));
        }

    }
}

resources/views/customer/home.blade.php
@extends('layouts.customer')
@section('title','Beranda')
@section('content')
    <div class="slider-area ">
          @if (session('success'))
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-check"></i> Success!</h5>
                {{session('success')}}
            </div>
          @endif
          
            <!-- Mobile Menu -->
            <div class="single-slider slider-height2  hero-overly d-flex align-items-center" style="min-height: 600px" data-background="{{asset('customers/img/hero/about_hero.jpg')}}">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-8">
                          
                            <div class="hero-cap text-left">
                                <h2>Undangan nikah online gratis dengan ngantenYuks.</h2>
                                <p style="color: white">Buat dan bagikan undangan pernikahan kamu dengan berbagai pilihan tampilan undangan yang menarik dan pastinya gratis hanya di sini.</p>
                                <a href="{{route('customer.buatundangan')}}"><button class="genric-btn info circle">Buat Undangan Sekarang</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="whole-wrap" id="fitur">
            
            <div class="section-top-border">
                <div class="row">
                    <div class="col-md-2">
                        
                    </div>
                    <div class="col-md-8">
                        <div class="container box_1170">
                            <div class="text-center ">
                            <h1>FITUR APLIKASI</h1>
                            <p>Dengan fitur yang memudahkan, di Akanikah membuat undangan pernikahan online semudah menggeser mouse ditangan anda.</p>
                        </div>
                    </div>
                    <div class="col-md-2">
                       
                    </div>
                    
                </div>
                
            </div>
            </div>
                <div class="section-top-border">
                    <div class="row">
                        <div class="col-md-2">
                            
                        </div>
                        <div class="col-md-3">
                            <img src="customers/img/illust/cepat.png" alt="" class="img-fluid">
                        </div>
                        <div class="col-md-5">
                            <h2>Mudah dan cepat</h2>
                            <p>Membuat undangan pernikahan online cepat, mudah dan pastinya gratis. Hanya beberapa menit dengan mengisi form registrasi maka undangan kamu akan siap untuk di bagikan keseluruh keluarga, sahabat dan kolegamu.
                                </p>
                        </div>
                        <div class="col-md-2">
                           
                        </div>
                        
                    </div>
                    
                   
                </div>
                <div class="section-top-border">
                    <div class="row" >
                        <div class="col-md-2">
                            
                        </div>
                        
                        <div class="col-md-5">
                            <h2>Subdomain unik</h2>
                            <p>Akanikah akan memberikan subdomain URL unik untuk website undangan kamu, dengan menggunakan kata-kata sesuai dengan keinginan kamu seperti akudandia.akanikah.com.
                                </p>
                        </div>
                        <div class="col-md-3">
                            <img src="customers/img/illust/website.png" alt="" class="img-fluid">
                        </div>
                        <div class="col-md-2">
                           
                        </div>
                        
                    </div>
                </div>
                <div class="section-top-border mt-4" >
                        <div class="row">
                            <div class="col-md-2">
                                
                            </div>
                            <div class="col-md-3">
                                <img src="customers/img/illust/media.png" alt="" class="img-fluid">
                            </div>
                            <div class="col-md-5">
                                <h2>Share dimana saja dan kapan saja</h2>
                                <p>Membuat undangan pernikahan online cepat, mudah dan pastinya gratis. Hanya beberapa menit dengan mengisi form registrasi maka undangan kamu akan siap untuk di bagikan keseluruh keluarga, sahabat dan kolegamu.
                                    </p>
                            </div>
                            <div class="col-md-2">
                               
                            </div>
                            
                        </div>
                </div>
                <div class="section-top-border mt-4" >
                    <div class="row">
                        <div class="col-md-4">
                            
                        </div>
                        <div class="col-md-4">
                            <a href="{{route('customer.buatundangan')}}"><button class="genric-btn info circle e-large btn-block">Buat Undangan Sekarang</button></a>
                        </div>
                        <div class="col-md-4">
                           
                        </div>
                        
                    </div>
                 </div>
                
               
            </div>
        </div>
@endsection

resources/views/customer/register.blade.php
@extends('layouts.customer')
@section('title','Registrasi ')
@section('content')

<div class="container mb-30">
    <div class="card">
    <div class="card-body">
        @if (count($errors)>0)
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-ban"></i> Validasi!</h5>
                @foreach ($errors->all() as $e)
                    {{$e}} 
                @endforeach
            </div>
        @endif
        <h5 class="card-title">Data Pasangan</h5>
        <form action="{{route('customer.tambahundangan')}}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="row">
              <div class="col">
                <div class="mt-10">
                    <label for="">Nama Pria</label>
                    <input type="text" name="guy_nickname" placeholder="Nama Pria"
                        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Nama Pria'" required
                        class="single-input">
                </div>
              </div>
              <div class="col">
                <div class="mt-10">
                    <label for="">Nama Wanita</label>
                    <input type="text" name="girl_nickname" placeholder="Nama Wanita"
                        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Nama Wanita'" required
                        class="single-input">
                </div>
              </div>
              
            </div>
            <div class="row">
                <div class="col">
                    <div class="input-group-icon mt-10">
                        <div class="icon"><i class="fa fa-globe" aria-hidden="true"></i></div>
                        <div class="form-select" id="default-select">
                            <select name="agama">
                                <option value="">Pilih Agama</option>
                                @foreach ($agama as $key )
                                    <option value="{{$key->id}}">{{$key->agama}}</option>
                                @endforeach
                                
                            </select>
                        </div>
                    </div>
                </div>
                
              </div>
            <h5 class="card-title mt-4">Waktu dan Tempat Pernikahan</h5>
            <div class="row">
                <div class="col">
                    <div class="mt-10">
                        <label for="">Tanggal</label>
                        <input type="date" name="date" placeholder="Pilih Tanggal"
                            onfocus="this.placeholder = ''" onblur="this.placeholder = 'Pilih Tanggal'" required
                            class="single-input">
                    </div>
                </div>
               
                <div class="col">
                    <div class="mt-10">
                        <label for="">Waktu Mulai</label>
                        <input type="time" name="time" placeholder="Waktu Mulai"
                            onfocus="this.placeholder = ''" onblur="this.placeholder = 'Waktu Mulai'" required
                            class="single-input">
                    </div>
                  </div>
                  <div class="col">
                    <div class="mt-10">
                        <label for="">Tempat</label>
                        <input type="text" name="address" placeholder="Tempat Pernikahan"
                            onfocus="this.placeholder = ''" onblur="this.placeholder = 'Tempat Pernikahan'" required
                            class="single-input">
                    </div>
                  </div>
              </div>
              <div class="row mt-4">
                  <div class="col">
                    <div class="mt-10">
                        <label for="">Pilih Lokasi pada Maps ( Pindahkan Marker untuk Memilih Lokasi )</label>
                        {{-- <input type="text" name="google_maps" placeholder="Masukan link google maps"
                            onfocus="this.placeholder = ''" onblur="this.placeholder = 'Link google maps'" required
                            class="single-input"> --}}
                        <div id="mapid" style="height: 300px;"></div>
                        {{-- <input type="hidden" id="latitude" name="latitude" required>
                        <input type="hidden" id="longitude" name="longitude" required> --}}
                    </div>
                </div>
              </div>
              <div class="row mt-4">
                <div class="col">
                  <div class="mt-10">
                      <label for="">Latitude</label>
                      <input type="text" name="latitude" id="latitude" readonly class="single-input">
                  </div>
                </div>
                <div class="col">
                  <div class="mt-10">
                      <label for="">Longitude</label>
                      <input type="text" name="longitude" id="longitude"  readonly class="single-input">
                  </div>
                </div>
                
              </div>
              <div class="row mt-4">
                <div class="col">
                    <div class="mt-10">
                        <label for="basic-url">Nomor Telepon</label>
                            <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon3">+62</span>
                            </div>
                            <input required type="text" name="whatsapp_number" class="form-control" id="basic-url" aria-describedby="basic-addon3">
                            </div>
                        </div>
              </div>
              <div class="col">
                  <div class="mt-10">
                <label for="basic-url">Masukan Subdomain</label>
                    <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon3">https://ngantenyuk.widianapw.com/</span>
                    </div>
                    <input required type="text" class="form-control" name="subdomain" id="basic-url" aria-describedby="basic-addon3">
                    </div>
                </div>
              </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="mt-10">
                        <label for="">Photo Cover</label>
                        <div class="custom-file">
                            <input required type="file" accept="image/x-png,image/gif,image/jpeg" name="gambar[]" class="custom-file-input" id="gambar">
                            <label class="custom-file-label" for="customFile">Choose file</label>
                          </div>
                    </div>
                    
                </div>
                <div class="col">
                    <div class="mt-10">
                        <label for="">Gallery</label>
                        <div class="custom-file">
                            <input required type="file" accept="image/x-png,image/gif,image/jpeg" name="gallery[]" class="custom-file-input" id="gallery" multiple="multiple">
                            <label class="custom-file-label" for="customFile">Choose file</label>
                          </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="mt-20">
                        <label for="">Bukti Pembayaran: <br><b>(Transfer Rp 100.000 ke rekening BNI 04893123123 atas nama Dewa Putu Pranata Swarimbawa)</b></label>
                        <div class="custom-file">
                            <input required type="file" accept="image/x-png,image/gif,image/jpeg" name="bukti_pembayaran[]" class="custom-file-input" id="gallery">
                            <label class="custom-file-label" for="customFile">Choose file</label>
                          </div>
                    </div>
                </div>
            </div>
            <input type="submit" class="btn btn-primary mt-4" value="SUBMIT">
          </form>
        {{-- <a href="#" class="btn btn-primary">Go somewhere</a> --}}
    </div>
</div>
</div>
@endsection

@section('js')
    <script>
        var mymap = L.map('mapid').setView([-8.655924, 115.216934], 13);
        L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            maxZoom: 20,
            id: 'mapbox/streets-v11',
            tileSize: 512,
            zoomOffset: -1,
            accessToken: 'pk.eyJ1Ijoid2lkaWFuYXB3IiwiYSI6ImNrNm95c2pydjFnbWczbHBibGNtMDNoZzMifQ.kHoE5-gMwNgEDCrJQ3fqkQ'
        }).addTo(mymap);
        marker = new L.marker([-8.655924, 115.216934], {draggable:'true'}).addTo(mymap);
        $('#latitude').val(-8.655924);
        $('#longitude').val(115.216934);
        marker.on('dragend', function(event){
            var marker = event.target;
            var position = marker.getLatLng();
            console.log(position);
            marker.setLatLng(new L.LatLng(position.lat, position.lng),{draggable:'true'});
            mymap.panTo(new L.LatLng(position.lat, position.lng))
            $('#latitude').val(position.lat);
            $('#longitude').val(position.lng);
        });
    </script>
    <script>
        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function() {
          
          var fileName = $(this).val().split("\\").pop();
          var fileName1 = $(this).get(0).files.length;
          console.log(fileName1);
          if(fileName1>1){
            var text = fileName1 + " Gambar Terpilih";
            $(this).siblings(".custom-file-label").addClass("selected").html(text);
          }else{
          $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
          }
        });
        </script>

    
@endsection